services:
  echo-web:
    image: echo-web:latest
    build: .
    container_name: echo-web
    env_file:
      - .env
    environment:
      - TZ=America/Los_Angeles
    expose:
      - "3160"
    volumes:
      - ./inbound:/app/inbound
    restart: unless-stopped
